spring:
  profiles:
    active: local
  application:
    name: user-service

---
spring:
  profiles: local
  datasource:
    platform: h2
    url: jdbc:h2:mem:user;Mode=PostgreSQL
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 2021

---
spring:
  profiles: kubernetes
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_DATABASE}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    platform: postgres
    initialization-mode: always
    continue-on-error: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp.use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: update
    database: postgresql
server:
  port: 80